version: '3.4'
name: test-compose-services

services:
    rabbitmq:
        image: rabbitmq:3.13.0-management
        ports:
          - "5672:5672"  # RabbitMQ default port
          - "15672:15672"  # RabbitMQ management UI port
        hostname: rabbitmq_challenge_server
        container_name: "rabbitmq-challenge-server"
        environment:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest

    testdockerrabbit.firstapi:
        image: ${DOCKER_REGISTRY-}testdockerrabbitfirstapi
        container_name: "first-api"
        build:
          context: .
          dockerfile: TestDockerRabbit.FirstAPI/Dockerfile
        ports:
            - "3500:8080" # HTTP_PORT
            - "3501:8081" # HTTPS_PORT